server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/authorization?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
#          articles-client-oidc:
#            provider: spring
#            client-id: articles-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: openid, articles.read
#            client-name: articles-client-oidc
          internal-client:
            provider: spring
            client-id: internal-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: articles.read
            client-name: internal-client
        provider:
          spring:
            issuer-uri: http://auth-server:9000
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace